# Matrizes

## O Que São Matrizes?


Matrizes são arranjos de números, símbolos ou expressões, organizados em linhas e colunas. Elas são um conceito fundamental na Matemática, especialmente na álgebra linear, e têm diversas aplicações em ciências, engenharia, estatística e outras áreas. Abaixo, alguns pontos-chave sobre matrizes:

1. **Elementos**  
   Cada item em uma matriz é chamado de elemento. Os elementos podem ser números, mas também podem ser expressões mais complexas.

2. **Dimensões**  
   O tamanho de uma matriz é definido por suas linhas (horizontal) e colunas (vertical). Por exemplo, uma matriz de 3x2 tem 3 linhas e 2 colunas.

3. **Tipos de Matrizes**  
   Existem vários tipos, incluindo:  
   - Matrizes quadradas (mesmo número de linhas e colunas)  
   - Matrizes retangulares (número diferente de linhas e colunas)  
   - Matrizes diagonais (elementos fora da diagonal principal são todos zero)  
   - Entre outros tipos especiais

4. **Operações**  
   As matrizes podem ser somadas, subtraídas e multiplicadas entre si, seguindo regras específicas. SPor exemplo, a multiplicação de matrizes não é comutativa, ou seja, a ordem dos fatores altera o resultado.

5. **Determinante e Inversa**  
   Para algumas matrizes quadradas, pode-se calcular o determinante, uma propriedade que fornece informações importantes sobre a matriz. Matrizes com determinante diferente de zero possuem uma inversa, que é uma matriz que, ao ser multiplicada pela original, resulta na matriz identidade.

6. **Aplicações**  
   - Matrizes são usadas para resolver sistemas de equações lineares, onde cada linha pode representar uma equação e cada coluna uma variável desconhecida.  
   - Representam transformações lineares entre espaços vetoriais, como rotações, reflexões e escalonamentos em gráficos computacionais.  
   - São utilizadas em matemática avançada para encontrar autovalores e autovetores, úteis na análise de sistemas dinâmicos, mecânica quântica e redução de dimensionalidade em Machine Learning.  
   - Organizam e manipulam dados com múltiplas variáveis por observação, como em pesquisas: cada linha representa uma resposta individual, cada coluna uma pergunta.  
   - Fundamentais em modelos estatísticos lineares, como a regressão linear múltipla, representando variáveis dependentes e independentes.  
   - Matrizes de covariância e correlação ajudam a entender como diferentes variáveis estão relacionadas entre si. Cada elemento representa a covariância ou correlação entre um par de variáveis.

> Matrizes são estruturas essenciais para representar e manipular relações lineares entre variáveis, dados e transformações espaciais. Elas fornecem uma forma compacta e poderosa de resolver uma ampla variedade de problemas teóricos e práticos.



## Trabalhando com Escalares usando NumPy

In [1]:
import numpy as np

In [9]:
escalar1 = 2
escalar = np.array(2)
type(escalar1), type(escalar)

(int, numpy.ndarray)

In [10]:
print(escalar)

2


In [11]:
x = 2 + escalar
print(x)
type(x)

4


numpy.int64

In [18]:
escalar.shape

()

## Vetores

In [15]:
vetor = np.array([1, 2, 3])
type(vetor)

numpy.ndarray

In [16]:
print(vetor)

[1 2 3]


In [17]:
vetor.shape

(3,)

O shape (3,) indica 3 elementos de uma estrutura unidimensional

In [24]:
vetor[0]

np.int64(1)

## Matrizes

In [25]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
type(m)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
m.shape

(3, 3)

O shape (3,3) indica que é uma matriz com 2 dimensões, cada dimensão tem 3 elementos.

In [28]:
print(m[1, 2])

6


## Tensores

Tensores são como vetores e matrizes, mas podem ter n dimensões.

In [43]:
t = np.array([[[1, 2, 2], [3, 4, 4]],\
               [[5, 6, 5], [7, 8, 8]],\
               [[9, 10, 9], [11, 8, 9]]])
print(t)
t.shape

[[[ 1  2  2]
  [ 3  4  4]]

 [[ 5  6  5]
  [ 7  8  8]]

 [[ 9 10  9]
  [11  8  9]]]


(3, 2, 3)

### Mudança de shape entre vetores, matrizes e tensores

In [46]:
vec = np.array([1, 2, 3, 4, 5])
print(vec)
vec.shape

[1 2 3 4 5]


(5,)

In [49]:
x = vec.reshape(5, 1)
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]
 [5]]


(5, 1)

Uso de `flatten` para transformar tensor em vetor:

In [ ]:
t = np.array([[[1, 2], [3, 4]],
             [[5, 6], [7, 8]]])

vetor_flat = t.flatten()
print(vetor_flat)

[1 2 3 4 5 6 7 8]


Cnverter em matriz

In [54]:
matriz = t.reshape(2, 4)
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [55]:
matriz = t.reshape(4, 2)
print(matriz)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## ELement-wise
### Operações Element-wise com Vetores

In [56]:
valores = np.array([1, 2, 3, 4, 5])

valores = valores + 10
print(valores)

[11 12 13 14 15]


In [ ]:
valores = np.array([1, 2, 3, 4, 5])

# outro método,  mais otimizado
valores = np.add(valores, 10)
print(valores)

[11 12 13 14 15]


In [61]:
valores *= 0
print(valores)

[0 0 0 0 0]


### Operações Element-wise com Matrizes

In [64]:
x = np.array([[1, 2], [5, 6]])
print(x)

[[1 2]
 [5 6]]


In [69]:
y = np.array([[2, 4], [3, 7]])
print(y)

[[2 4]
 [3 7]]


In [70]:
x + y

array([[ 3,  6],
       [ 8, 13]])

In [72]:
y + 5

array([[ 7,  9],
       [ 8, 12]])

In [73]:
x + y + 10

array([[13, 16],
       [18, 23]])

In [75]:
(x + y) / 10

array([[0.3, 0.6],
       [0.8, 1.3]])

## MUltiplicação de matrizes

### Multiplicação elemento a elemento (elemnt-wise)

**x * y**
multiplicando elemento a elemento:

_obs: não é multiplicação de matrizes_

 Para que a multiplicação elemento a elemento funcione, as matrizes envolvidas devem ter o mesmo tamanho (número de linhas e colunas)

In [77]:
print(x)
print(y)
x * y

[[1 2]
 [5 6]]
[[2 4]
 [3 7]]


array([[ 2,  8],
       [15, 42]])

### Multiplicação de Matrizes

**np.matmul(x, y)** ou  **x @ y** é a multiplicação de matrizes própriamente dita.

In [78]:
np.matmul(x, y)

array([[ 8, 18],
       [28, 62]])

In [79]:
x @ y

array([[ 8, 18],
       [28, 62]])

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

A definição de multiplicação de matrizes indica uma multiplicação linha por coluna, onde as entradas na i-ésima linha de A são multiplicados pelas entradas correspondentes no jth coluna de B e, em seguida, somando os resultados.

A multiplicação de matrizes NÃO é comutativa.

#### Produto matricial
**np.dot(x, y)**

 Para matrizes **bidimensionais**, np.dot(x, y) é equivalente a np.matmul(x, y).
  Calcula o produto matricial de x e y.

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

O produto escalar (dot product) é a soma dos produtos dos elementos correspondentes nas duas matrizes. Para obter o produto escalar, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.


In [85]:
np.dot(x, y)

array([[ 8, 18],
       [28, 62]])


**np.dot(x, x.T)**: Aqui, x.T é a transposta de x. Esta operação realiza o produto matricial de x com sua transposta. O resultado é uma matriz que representa, de certa forma, o "produto escalar" da matriz com ela mesma, mas em termos de suas linhas ou colunas, dependendo da orientação da multiplicação.


In [87]:
np.dot(x, x.T)

array([[ 5, 17],
       [17, 61]])

#### Magnitude da Matriz

**np.sqrt(np.sum(x ** 2))**: Esta expressão calcula a norma Frobenius da matriz x. Primeiro, eleva cada elemento de x ao quadrado e soma todos esses quadrados. Em seguida, calcula a raiz quadrada do resultado. Isso dá uma medida geral da magnitude da matriz x.

In [89]:
mag = np.sqrt(np.sum(x ** 2))
print(mag)

8.12403840463596


**np.cross(x, y)**: Esta operação calcula o produto vetorial (ou produto cruzado) de x e y. Como x e y são matrizes 2x2, a função np.cross tratará as linhas de cada matriz como vetores e calculará o produto vetorial linha a linha.


In [90]:
np.cross(x, y)

/tmp/ipykernel_2402442/2907437548.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(x, y)


array([ 0, 17])

## Conceitos de Broadcasting do NumPy
Broadcasting no NumPy é um recurso que permite que operações aritméticas sejam realizadas em arrays de diferentes formas e tamanhos.

Esse processo envolve automaticamente "estender" um ou ambos os arrays envolvidos na operação para que eles tenham a mesma forma, permitindo assim que as operações sejam realizadas de maneira elementar.

### Regras de Broadcasting

- Se os arrays não tiverem o mesmo número de dimensões, a forma do array com menos dimensões é preenchida com uns à esquerda.

- Se o tamanho das dimensões corresponder ou se uma das dimensões for 1, o broadcasting será aplicado. Se uma dimensão de um array for 1 e a do outro array for maior que 1, o primeiro array se comportará como se tivesse o tamanho da maior dimensão.

- Se em qualquer dimensão os tamanhos forem diferentes e nenhum deles for 1, ocorrerá um erro, pois o broadcasting não pode ser aplicado.