# Matrizes

In [2]:
# Imports
import numpy as np
import sympy as sym

## Transposta de matriz com Numpy

In [5]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m_t = m.T

In [6]:
print("Matriz Original:")
print(m)
print("\nMatriz Transposta:")
print(m_t)

Matriz Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriz Transposta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Atenção: ao alterar um valor na matriz transposta salva, o valor é alterado também na matriz original.

In [7]:
m_t[0, 2] = 200
print("Matriz Transposta:")
print(m_t)

print("Matriz Original:")
print(m)

Matriz Transposta:
[[  1   5 200]
 [  2   6  10]
 [  3   7  11]
 [  4   8  12]]
Matriz Original:
[[  1   2   3   4]
 [  5   6   7   8]
 [200  10  11  12]]


Para evitar que altere a matriz original, usa-se `.copy()`

In [9]:
m_t = m.T.copy()

In [10]:
m_t[0, 2] = 29

print("Matriz Transposta:")
print(m_t)
print("Matriz Original:")
print(m)

Matriz Transposta:
[[ 1  5 29]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Matriz Original:
[[  1   2   3   4]
 [  5   6   7   8]
 [200  10  11  12]]


### Exemplo do uso da transposta em Algoritmos de redes neurais

In [15]:
inputs = np.array([[-0.24, 0.52, 0.13, 0.27]])
inputs.shape

(1, 4)

In [20]:
pesos = np.array([[0.02, 0.001, -0.03, 0.036], 
                 [0.01, 0.02, 0.03, -0.04], 
                 [-0.02, 0.03, 0.01, 0.02]])
print(pesos)
pesos.shape

[[ 0.02   0.001 -0.03   0.036]
 [ 0.01   0.02   0.03  -0.04 ]
 [-0.02   0.03   0.01   0.02 ]]


(3, 4)

Os pesos são multiplicados aos inputs nas camadas das redes neurais, logo precisamos multiplicar pesos por inputs. 

Para multiplicar pelo pelos pesos é necessário fazer a transposta da matriz para que o shape das matrizes sejam compatíveis.

In [24]:
np.matmul(inputs, pesos.T)

array([[0.00154, 0.0011 , 0.0271 ]])

Também funciona com a transposta da matriz de inputs trocando a ordem dos fatores:

In [25]:
np.matmul(pesos, inputs.T)

array([[0.00154],
       [0.0011 ],
       [0.0271 ]])

## Determinante de Matriz


O determinante de uma matriz é um valor que pode ser calculado a partir dos elementos de uma matriz quadrada.

Este valor é muito importante em diversas áreas da Matemática e Ciência de Dados, pois possui várias aplicações práticas e teóricas.

### Matriz 2×2

Dada a matriz:

$$
A = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

O determinante é calculado como:

$$
\det(A) = ad - bc
$$

### Propriedades

- O determinante de uma matriz identidade é sempre 1.

- Multiplicar uma linha de uma matriz por um escalar multiplica o determinante pelo mesmo escalar.

- Se você trocar duas linhas de uma matriz, o determinante muda de sinal.

- O determinante de uma matriz é zero se as linhas ou colunas são linearmente dependentes (ou seja, uma linha ou coluna pode ser expressa como uma combinação linear das outras).


### Aplicações em Matrizes

- **Inversão de Matriz**: Uma matriz quadrada é invertível se e apenas se seu determinante não é zero.

- **Solução de Sistemas Lineares**: O método de Cramer usa determinantes para resolver sistemas de equações lineares.

- **Geometria**: O determinante pode ser usado para calcular a área (em 2D) ou volume (em 3D) de formas geométricas definidas por pontos.


### Cálculo de Matrizes Maiores

Para matrizes maiores que 3x3, o cálculo do determinante envolve a decomposição da matriz em matrizes menores (método de expansão por cofatores) ou utilizando operações de linha para transformá-la em uma forma mais simples (como a forma escalonada).

### Calculando Determinante com NumPy e SymPy

Usando NumPy:

In [37]:
# matrix 2x2
ma = np.array([[1, 3], [3, 3]])

In [38]:
det_1 = np.linalg.det(ma)
print(det_1)

-6.0


Usando o SymPy:

In [ ]:
ma_sym = sym.Matrix(ma)
det_2 = ma_sym.det()
print(det_2)

-6


Fórmula do determinante:

In [42]:
A = np.array([['a', 'b'], ['c', 'd']])
print("Matriz A:")
print(A)

Matriz A:
[['a' 'b']
 ['c' 'd']]


A Fórmula para o determinante de uma matriz 2x2 é:

Det(A) = ad - bc

In [44]:
matriz = np.array([[1, 2], [3, 4]])
print(matriz)

[[1 2]
 [3 4]]


In [45]:
det_3 = (1 * 4) - (2 * 3)
print(det_3)

-2


Fórmula para outras dimensões:

https://www.mathsisfun.com/algebra/matrix-determinant.html

## Matriz Inversa

A matriz inversa é uma matriz que quando multiplicada por uma matriz resulta na matriz identidade.

Seja $A$ uma matriz quadrada de ordem $n$. Dizemos que uma matriz $A^{-1}$ é a **inversa de $A$** se:

$$
A \cdot A^{-1} = A^{-1} \cdot A = I_n
$$

Onde:

- $A$ é uma matriz quadrada $n \times n$
- $A^{-1}$ é a matriz inversa de $A$
- $I_n$ é a matriz identidade de ordem $n$


Observações:

A inversa de uma matriz só existe se a matriz é não-singular, ou seja, se o determinante da matriz é diferente de zero.

Se o determinante de uma matriz é zero, ela não tem inversa.

- Nem toda matriz possui inversa.
- Se $\det(A) = 0$, dizemos que $A$ é **singular** e **não possui inversa**.
- A inversa de uma matriz é única.
- Se $A^{-1}$ existe, então:

$$
(A^{-1})^{-1} = A
$$

$$
(A^T)^{-1} = (A^{-1})^T
$$

$$
(AB)^{-1} = B^{-1} A^{-1}
$$

In [46]:
matriz

array([[1, 2],
       [3, 4]])

In [48]:
inversa = np.linalg.inv(matriz)
inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [49]:
np.linalg.inv(inversa)

array([[1., 2.],
       [3., 4.]])

#### Quando Usamos Matriz Inversa em Machine Learning?

A matriz inversa é usada em aprendizado de máquina (Machine Learning) principalmente nos seguintes contextos:

**Regressão Linear**: Na regressão linear, um dos métodos para calcular os coeficientes (pesos) do modelo é através do método dos mínimos quadrados. Este método frequentemente envolve inverter uma matriz (a matriz X transposta multiplicada por X, onde X é a matriz de características). A inversão desta matriz permite resolver a equação normal para encontrar os coeficientes que minimizam o erro do modelo.

**Regularização**: Em alguns casos, como na regressão ridge ou LASSO, a inversão de matrizes é parte do processo de regularização. A regularização é usada para evitar o sobreajuste (overfitting) adicionando uma penalidade ao tamanho dos coeficientes. Na regressão ridge, por exemplo, a inversão de matrizes é usada para calcular os coeficientes de forma que eles sejam penalizados.

**Análise de Componentes Principais (PCA)**: No PCA, que é uma técnica de redução de dimensionalidade, a inversão de matrizes é usada no cálculo dos autovalores e autovetores da matriz de covariância. Isso é essencial para identificar as direções (componentes principais) que capturam a maior variação nos dados.

**Algoritmos Baseados em Distância**: Em algoritmos que usam medidas de distância, como o K-Nearest Neighbors (KNN) ou algoritmos de clustering, a inversão de matrizes pode ser usada em contextos específicos, como quando se ajusta uma métrica de distância ou se realiza uma transformação de características.

**Redes Neurais**: Em redes neurais, a inversão de matrizes pode ser usada em algumas técnicas de otimização, como o método de Newton, embora métodos mais modernos geralmente utilizem gradientes e não requeiram inversão de matrizes.

É importante notar que a inversão de matrizes pode ser computacionalmente custosa e, em alguns casos, pode levar a problemas de instabilidade numérica. Por isso, em prática, muitas vezes são usadas técnicas alternativas para evitar a inversão direta de matrizes, como a decomposição em valores singulares (SVD) ou métodos iterativos.

## Escalonamento de Matrizes

### O Que é Escalonamento de Matrizes?

Escalonamento de matrizes é um processo usado na álgebra linear para transformar uma matriz em uma forma mais simples, conhecida como "forma escalonada".

Este processo facilita a solução de sistemas de equações lineares, o cálculo do determinante, entre outras operações.

Existem dois tipos principais de formas escalonadas:

1. Forma Escalonada: Nesta forma, cada linha não-nula começa com um número de zeros que é pelo menos um a mais do que o número de zeros no início da linha acima dela. Além disso, todas as linhas que contêm apenas zeros, se houver, estão na parte inferior da matriz.
2. Forma Escalonada Reduzida: É uma versão mais restrita da forma escalonada. Aqui, o primeiro número não-zero em cada linha não-nula (chamado de pivô) é 1, e este 1 é o único número não-zero em sua coluna.

O processo de escalonamento envolve o uso de operações elementares de linha, que são:

- Trocar a posição de duas linhas.
- Multiplicar todos os elementos de uma linha por um número não-nulo.
- Adicionar a uma linha um múltiplo de outra linha.

Considere a seguinte matriz:

$$
A = \begin{bmatrix}
1 & 2 & -1 \\
2 & 3 & 1 \\
-1 & 0 & 2 \\
\end{bmatrix}
$$

Vamos aplicar operações elementares para escaloná-la:

- Passo 1: Eliminar os elementos abaixo do pivô da 1ª coluna

Usamos a 1ª linha como pivô. Para zerar o elemento na posição (2,1):

$$
L_2 \leftarrow L_2 - 2L_1
$$

$$
\begin{bmatrix}
1 & 2 & -1 \\
0 & -1 & 3 \\
-1 & 0 & 2 \\
\end{bmatrix}
$$

Agora, para zerar o elemento na posição (3,1):

$$
L_3 \leftarrow L_3 + L_1
$$

$$
\begin{bmatrix}
1 & 2 & -1 \\
0 & -1 & 3 \\
0 & 2 & 1 \\
\end{bmatrix}
$$

- Passo 2: Eliminar o elemento abaixo do pivô da 2ª coluna

Usamos a 2ª linha como pivô. Para zerar o elemento na posição (3,2):

$$
L_3 \leftarrow L_3 + 2L_2
$$

$$
\begin{bmatrix}
1 & 2 & -1 \\
0 & -1 & 3 \\
0 & 0 & 7 \\
\end{bmatrix}
$$

Agora a matriz está na **forma escalonada**, com zeros abaixo da diagonal principal.

 Observações

- As operações elementares permitidas são:
  - Trocar duas linhas.
  - Multiplicar uma linha por um número diferente de zero.
  - Somar/subtrair múltiplos de linhas.

- O objetivo do escalonamento é facilitar operações como:
  - Resolução de sistemas lineares pelo método de Gauss.
  - Cálculo de determinante.
  - Cálculo de matriz inversa.

### Resolvendo Sistema de Equações Lineares com Eliminação Gaussiana em Python

Aqui está um exemplo de código Python que usa o pacote NumPy para escalonar uma matriz e resolver um sistema de equações lineares usando o método de eliminação gaussiana. Antes criaremos o processo manualmente.

Este método consiste em transformar o sistema de equações em uma forma escalonada ou reduzida (matriz triangular superior) por meio de operações elementares nas linhas e depois resolver as equações de cima para baixo.

Considere o dataset abaixo como um exemplo didático:

Dados originais:

- Idade, Salario, Número de Filhos, Número de Anos Para Promoção
- 34, 10000, 2, 1
- 42, 12000, 3, 3
- 27, 8000, 5, 9


Dados normalizados:

- Idade, Salario, Número de Filhos, Número de Anos Para Promoção
- 2, 3, 2, 1
- 4, 1, 3, 3
- 1, 2, 5, 9

Divisão entrada/saída:

- Variáveis de entrada: Idade, Salario, Número de Filhos
- Variável de saída: Número de Anos Para Promoção

Vamos colocar os dados no formato de equações e resolver o seguinte sistema de equações como exemplo:

- 2x + 3y + 2z = 1
- 4x + y + 3z = 3
- x + 2y + 5z = 9

O objetivo é encontrar os valores de x, y e z que satisfazem todas as três equações simultaneamente. 

In [23]:
# Matriz que representa dados de entrada
A = np.array([[2, 3, 2],
              [4, 1, 3],
              [1, 2, 5]]).astype('float')

# Vetor que representa dados de saída
b = np.array([1, 3, 9]).astype('float')

In [24]:
# Formando a matriz combinando A e b
Ab = np.hstack([A, b.reshape(-1, 1)])

Ab

array([[2., 3., 2., 1.],
       [4., 1., 3., 3.],
       [1., 2., 5., 9.]])

In [25]:
n=len(b)
n

3

In [26]:
for i in range(n):
     # Escolhendo o maior pivô para estabilidade numérica
    max_row = np.argmax(np.abs(Ab[i:, i])) + i
    Ab[[i, max_row]] = Ab[[max_row, i]]

Ab
    

array([[4., 1., 3., 3.],
       [2., 3., 2., 1.],
       [1., 2., 5., 9.]])

In [27]:
for i in range(n): 
     # Tornando zero os elementos abaixo do pivô
    for j in range(i + 1, n):
        Ab[j] = Ab[j] - Ab[j, i] / Ab[i, i] * Ab[i]

Ab

array([[ 4. ,  1. ,  3. ,  3. ],
       [ 0. ,  2.5,  0.5, -0.5],
       [ 0. ,  0. ,  3.9,  8.6]])

In [28]:
# Matriz de zeros
mat = np.zeros(n)
    
 # Substituição para trás
for i in range(n - 1, -1, -1):
 mat[i] = (Ab[i, -1] - np.dot(Ab[i, i + 1:n], mat[i + 1:n])) / Ab[i, i]

mat

array([-0.74358974, -0.64102564,  2.20512821])

In [29]:
x, y, z = mat

Resultados da equação:
- 2x + 3y + 2z = 1
- 4x + y + 3z = 3
- x + 2y + 5z = 9

In [30]:
print(2*x + 3*y + 2*z)
print(4*x + y + 3*z)
print(x + 2*y + 5*z)

1.0
3.0000000000000004
9.0


Usando NumPy:

In [66]:
solucao = np.linalg.solve(A,b)

solucao

array([-0.74358974, -0.64102564,  2.20512821])

In [67]:
x, y, z = solucao

In [68]:
print(2*x + 3*y + 2*z)
print(4*x + y + 3*z)
print(x + 2*y + 5*z)

1.0
3.0
9.0


## Autovalores e Autovetores

Seja $A$ uma matriz n x n. 
Um autovalor (ou valor próprio) $\lambda$ e um autovetor $\vec{v} \ne \vec{0}$ são definidos pela equação:

$$A\vec{x} = \lambda \vec{x}$$

O vetor $\vec{x}$ é chamado de autovetor de a correspondente a $\lambda$

- O autovetor $\vec{x}$ é uma direção que não muda após a transformação pela matriz $A$.

- O autovalor $\lambda$ indica quanto o vetor foi esticado ou encolhido:

    - Se $\lambda > 1$: vetor cresce

    - Se $0 < \lambda < 1$: vetor encolhe

    - Se $\lambda < 0$: vetor inverte de direção

In [42]:
a = np.array([[2, 2, 1], [1, 3, 1], [1, 2, 2]])

In [53]:
# Autovalores e autovetores
avl, avt = np.linalg.eig(a)

# Determinante 
det = np.linalg.det(a).round()

In [54]:
# Autovalores
print(avl)

[5. 1. 1.]


In [56]:
print(det)

5.0


O produto dos autovalores  (5x1x1) é igual ao determinante (5).

In [45]:
# Autovetores
avt

array([[-0.57735027, -0.90453403,  0.82529864],
       [-0.57735027,  0.30151134, -0.52125218],
       [-0.57735027,  0.30151134,  0.21720572]])

Autovalores e autovetores são extremamente úteis na Análise de Componentes Principais (PCA). No PCA, os autovetores da matriz de correlação ou covariância representam os componentes principais (as direções de variância máxima) e os autovalores correspondentes representam a quantidade de variação explicada por cada componente principal. 

Vamos criar uma matriz 3x3 e realizar os seguintes passos:

- Calcular os autovalores e autovetores da matriz.
- Mostrar como uma matriz pode ser aproximada usando apenas um dos seus autovetores e autovalores (essencial em PCA, por exemplo).

In [58]:
matriz = np.array([[2, 0, 0], [0, 3, 4], [0, 4, 9]])
matriz

array([[2, 0, 0],
       [0, 3, 4],
       [0, 4, 9]])

In [59]:
matriz.shape

(3, 3)

In [65]:
# Calculando autovalores e autovetores
autovalores_B, autovetores_B = np.linalg.eig(matriz)
autovalores_B, autovetores_B 

(array([11.,  1.,  2.]),
 array([[ 0.        ,  0.        ,  1.        ],
        [ 0.4472136 ,  0.89442719,  0.        ],
        [ 0.89442719, -0.4472136 ,  0.        ]]))

- Verificar a propriedade Av=λv, onde A é a matriz, v é um autovetor e λ é o autovalor correspondente.

In [ ]:
[matriz @ autovetores_B[:, i] for i in range(3)]

[array([0.        , 4.91934955, 9.8386991 ]),
 array([ 0.        ,  0.89442719, -0.4472136 ]),
 array([2., 0., 0.])]

In [68]:
[autovalores_B[i] * autovetores_B[:, i] for i in range(3)]

[array([0.        , 4.91934955, 9.8386991 ]),
 array([ 0.        ,  0.89442719, -0.4472136 ]),
 array([2., 0., 0.])]

- Mostrar como uma matriz pode ser aproximada usando apenas um dos seus autovetores e autovalores (essencial em PCA, por exemplo).

In [74]:
# Aproximação da matriz usando apenas um autovetor e autovalor
# Aqui, usaremos o primeiro autovalor e autovetor
aproximacao = np.outer(autovetores_B[:, 0], autovetores_B[:, 0]) * autovalores_B[0]
aproximacao

array([[0. , 0. , 0. ],
       [0. , 2.2, 4.4],
       [0. , 4.4, 8.8]])

## Redução de dimensionalidade com PCA Usando Autovalores e Autovetores

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits import Axes3D 

In [97]:
X = np.random.randn(100,3)

In [ ]:
cov_matriz = np.cov(X.T)
cov_matriz