# Matrizes

In [31]:
# Imports
import numpy as np
import sympy as sym

## Transposta de matriz com Numpy

In [5]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m_t = m.T

In [6]:
print("Matriz Original:")
print(m)
print("\nMatriz Transposta:")
print(m_t)

Matriz Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriz Transposta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Atenção: ao alterar um valor na matriz transposta salva, o valor é alterado também na matriz original.

In [7]:
m_t[0, 2] = 200
print("Matriz Transposta:")
print(m_t)

print("Matriz Original:")
print(m)

Matriz Transposta:
[[  1   5 200]
 [  2   6  10]
 [  3   7  11]
 [  4   8  12]]
Matriz Original:
[[  1   2   3   4]
 [  5   6   7   8]
 [200  10  11  12]]


Para evitar que altere a matriz original, usa-se `.copy()`

In [9]:
m_t = m.T.copy()

In [10]:
m_t[0, 2] = 29

print("Matriz Transposta:")
print(m_t)
print("Matriz Original:")
print(m)

Matriz Transposta:
[[ 1  5 29]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Matriz Original:
[[  1   2   3   4]
 [  5   6   7   8]
 [200  10  11  12]]


### Exemplo do uso da transposta em Algoritmos de redes neurais

In [15]:
inputs = np.array([[-0.24, 0.52, 0.13, 0.27]])
inputs.shape

(1, 4)

In [20]:
pesos = np.array([[0.02, 0.001, -0.03, 0.036], 
                 [0.01, 0.02, 0.03, -0.04], 
                 [-0.02, 0.03, 0.01, 0.02]])
print(pesos)
pesos.shape

[[ 0.02   0.001 -0.03   0.036]
 [ 0.01   0.02   0.03  -0.04 ]
 [-0.02   0.03   0.01   0.02 ]]


(3, 4)

Os pesos são multiplicados aos inputs nas camadas das redes neurais, logo precisamos multiplicar pesos por inputs. 

Para multiplicar pelo pelos pesos é necessário fazer a transposta da matriz para que o shape das matrizes sejam compatíveis.

In [24]:
np.matmul(inputs, pesos.T)

array([[0.00154, 0.0011 , 0.0271 ]])

Também funciona com a transposta da matriz de inputs trocando a ordem dos fatores:

In [25]:
np.matmul(pesos, inputs.T)

array([[0.00154],
       [0.0011 ],
       [0.0271 ]])

## Determinante de Matriz


O determinante de uma matriz é um valor que pode ser calculado a partir dos elementos de uma matriz quadrada.

Este valor é muito importante em diversas áreas da Matemática e Ciência de Dados, pois possui várias aplicações práticas e teóricas.

### Matriz 2×2

Dada a matriz:

$$
A = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

O determinante é calculado como:

$$
\det(A) = ad - bc
$$

### Propriedades

- O determinante de uma matriz identidade é sempre 1.

- Multiplicar uma linha de uma matriz por um escalar multiplica o determinante pelo mesmo escalar.

- Se você trocar duas linhas de uma matriz, o determinante muda de sinal.

- O determinante de uma matriz é zero se as linhas ou colunas são linearmente dependentes (ou seja, uma linha ou coluna pode ser expressa como uma combinação linear das outras).


### Aplicações em Matrizes

- **Inversão de Matriz**: Uma matriz quadrada é invertível se e apenas se seu determinante não é zero.

- **Solução de Sistemas Lineares**: O método de Cramer usa determinantes para resolver sistemas de equações lineares.

- **Geometria**: O determinante pode ser usado para calcular a área (em 2D) ou volume (em 3D) de formas geométricas definidas por pontos.


### Cálculo de Matrizes Maiores

Para matrizes maiores que 3x3, o cálculo do determinante envolve a decomposição da matriz em matrizes menores (método de expansão por cofatores) ou utilizando operações de linha para transformá-la em uma forma mais simples (como a forma escalonada).

### Calculando Determinante com NumPy e SymPy

Usando NumPy:

In [37]:
# matrix 2x2
ma = np.array([[1, 3], [3, 3]])

In [38]:
det_1 = np.linalg.det(ma)
print(det_1)

-6.0


Usando o SymPy:

In [ ]:
ma_sym = sym.Matrix(ma)
det_2 = ma_sym.det()
print(det_2)

-6


Fórmula do determinante:

In [42]:
A = np.array([['a', 'b'], ['c', 'd']])
print("Matriz A:")
print(A)

Matriz A:
[['a' 'b']
 ['c' 'd']]


A Fórmula para o determinante de uma matriz 2x2 é:

Det(A) = ad - bc

In [44]:
matriz = np.array([[1, 2], [3, 4]])
print(matriz)

[[1 2]
 [3 4]]


In [45]:
det_3 = (1 * 4) - (2 * 3)
print(det_3)

-2


Fórmula para outras dimensões:

https://www.mathsisfun.com/algebra/matrix-determinant.html