# Rede Neural

### 1. Tipo de rede

O que esse algoritmo representa é uma rede neural artificial simples, equivalente a um perceptron logístico: 

- Há apenas uma camada (entrada -> saída).
- Não existem camadas ocultas.
- A saída é obtida aplicando a função *sigmóide*, que transforma o resultado em algo entre 0 e 1.

Na prática, essa rede resolve problemas de classificação binária linearmente separáveis.

### 2. Como ela “aprende”

O aprendizado segue a lógica de redes neurais, mas de forma reduzida:

#### 1. Entrada dos dados (**Forward pass**):

- Cada atributo de entrada é multiplicado por um peso (representando a importância desse atributo).
- Todos os atributos ponderados são somados, junto com um viés (bias), que ajusta a posição da fronteira de decisão.
- O resultado passa pela função sigmóide, que produz uma saída interpretada como probabilidade de pertencer à classe 1.

#### 2. Erro (Função de custo implícita):

- O erro é a diferença entre o valor previsto e o valor real.
- Ajuste dos parâmetros (Backpropagation simplificado): Calcula-se o gradiente (direção em que o erro cresce).
- Os pesos e o bias são atualizados na direção oposta (usando o gradiente descendente) para reduzir o erro.

### Desenvolvimento do Algoritmo de Rede Neural

In [2]:
import numpy as np  

Imagine que queremos classificar pessoas em “alto risco” ou “baixo risco” para um crédito bancário:

- Os atributos de entrada podem ser: renda, idade, histórico de dívidas.
- Cada atributo recebe um peso, indicando o quanto ele influencia a decisão.
- O algoritmo ajusta esses pesos com base nos exemplos de treino: se erra, ele corrige um pouco a importância atribuída a cada atributo.
- Depois de várias iterações, a rede encontra uma fronteira de decisão: de um lado, pessoas que devem ser classificadas como “baixo risco”; de outro, como “alto risco”.

In [3]:
class AlgoritmoRedeNeural:

    # Método construtor
    def __init__(self, taxa_aprendizado, num_interacoes):
        self.taxa_aprendizado = taxa_aprendizado
        self.num_interacoes = num_interacoes

        self.pesos = None
        self.bias = None

    def func_sigmoid(self, pred):
       sig = 1/(1+np.exp(-pred))
       return sig 
    
    def fit(self, X, y):

        num_registro, num_atributos = X.shape

        self.pesos = np.zeros(num_atributos)

        self.bias = 0

        for i in range(self.num_interacoes):
            
            print(f"Iteração {i+1}/{self.num_interacoes}")

            ## 1- Foward pass
            previsao = np.dot(X, self.pesos) + self.bias
            print(f"Previsão: {previsao}")
            previsao_final = self.func_sigmoid(previsao)
            print(f"Previsão Sigmoid: {previsao_final}")

            # Cálculo do erro
            erro = previsao_final - y
            print(f"Erro: {erro}")

            ## 2- Backward pass
            # Calculando o gradiente (derivada da função de custo em relação aos pesos e bias)
            dw = (1/num_registro) * np.dot(X.T, erro)
            db = (1/num_registro) * np.sum(previsao_final - y)

            # Atualização dos pesos e bias
            # pesos - taxa_aprendizado * gradiente
            self.pesos -= self.taxa_aprendizado * dw
            self.bias -= self.taxa_aprendizado * db

        print(f"Pesos atualizados: {self.pesos}")
        print(f"Bias atualizado: {self.bias}")
        print("\nTreinamento concluído.")
    
    def predict(self, X):
        previsao = np.dot(X, self.pesos) + self.bias
        previsao_final = self.func_sigmoid(previsao)
        print(f"Previsão antes da função sigmoid: {previsao}")
        print(f"Previsão após a função sigmoid (final): {previsao_final}")
        classe_prevista = [1 if i > 0.5 else 0 for i in previsao_final]
        return classe_prevista


Os dados de entrada representam, por exemplo, número de compras em uma transação comercial
Os dados de saída representam, por exemplo, se a transação foi ou não suspeita
- Classe 0 = Não é Transação Suspeita
- Classe 1 = É Transação Suspeita

In [4]:
# Temos 2 atributos (variáveis) e 8 registros (linhas ou observações ou exemplos)
entrada = np.array([[1, 2.5], [2, 3], [3, 5], [1, 4], [5, 6], [6, 7], [4, 5.5], [1.5, 2]])

# Temos 8 itens, um para cada linha dos dados de entrada
saida = np.array([0, 0, 1, 0, 1, 1, 1, 0])

# Dados de entrada e saída para treinar o modelo 
X_treino = np.array([[1, 2.5], [2, 3], [3, 5], [1, 4], [5, 6], [6, 7]])
y_treino = np.array([0, 0, 1, 0, 1, 1])

# Dados de teste (2 registros)
X_teste = np.array([[1.5, 2], [4, 5.5]])
y_teste = np.array([0, 1])

NameError: name 'np' is not defined

### Separando em treino e teste

In [129]:
X = entrada[:6]
y = saida[:6]

X,y

(array([[1. , 2.5],
        [2. , 3. ],
        [3. , 5. ],
        [1. , 4. ],
        [5. , 6. ],
        [6. , 7. ]]),
 array([0, 0, 1, 0, 1, 1]))

In [130]:
X_teste = entrada[6:]
y_teste = saida[6:]
X_teste,y_teste

(array([[4. , 5.5],
        [1.5, 2. ]]),
 array([1, 0]))

### Treinando o modelo

In [131]:
# Define os hiperparâmetros (controlam o processo de treinamento)
taxa_aprendizado = 0.01
num_iteracoes = 1000

In [132]:
# Cria uma instância da classe, ou seja, um objeto
modelo = AlgoritmoRedeNeural(taxa_aprendizado, num_iteracoes)

In [133]:
# Treina o modelo
modelo.fit(X_treino, y_treino)

Iteração 1/1000
Previsão: [0. 0. 0. 0. 0. 0.]
Previsão Sigmoid: [0.5 0.5 0.5 0.5 0.5 0.5]
Erro: [ 0.5  0.5 -0.5  0.5 -0.5 -0.5]
Iteração 2/1000
Previsão: [0.02604167 0.03791667 0.06041667 0.03666667 0.08416667 0.09958333]
Previsão Sigmoid: [0.50651005 0.50947803 0.51509957 0.50916564 0.52102925 0.52487528]
Erro: [ 0.50651005  0.50947803 -0.48490043  0.50916564 -0.47897075 -0.47512472]
Iteração 3/1000
Previsão: [0.04947764 0.07228945 0.11520833 0.06958471 0.16083195 0.19034611]
Previsão Sigmoid: [0.51236689 0.5180645  0.52877027 0.51738916 0.54012154 0.54744337]
Erro: [ 0.51236689  0.5180645  -0.47122973  0.51738916 -0.45987846 -0.45255663]
Iteração 4/1000
Previsão: [0.07055264 0.10345089 0.16490282 0.09910633 0.23069931 0.27311545]
Previsão Sigmoid: [0.51763085 0.52583968 0.54113254 0.52475632 0.55742038 0.56785758]
Erro: [ 0.51763085  0.52583968 -0.45886746  0.52475632 -0.44257962 -0.43214242]
Iteração 5/1000
Previsão: [0.08949285 0.1317084  0.20998812 0.12555702 0.29441922 0.34865616

In [134]:
modelo.pesos

array([ 1.25669221, -0.47321303])

In [135]:
# Faz previsões com o modelo treinado usando dados de teste
previsoes_teste = modelo.predict(X_teste)

Previsão antes da função sigmoid: [ 1.41004121 -0.07544372]
Previsão após a função sigmoid (final): [0.80377244 0.48114801]


In [140]:
print(y_teste, previsoes_teste)

[1 0] [1, 0]
