# Matrizes

## O Que São Matrizes?


Matrizes são arranjos de números, símbolos ou expressões, organizados em linhas e colunas. Elas são um conceito fundamental na Matemática, especialmente na álgebra linear, e têm diversas aplicações em ciências, engenharia, estatística e outras áreas. Abaixo, alguns pontos-chave sobre matrizes:

1. **Elementos**  
   Cada item em uma matriz é chamado de elemento. Os elementos podem ser números, mas também podem ser expressões mais complexas.

2. **Dimensões**  
   O tamanho de uma matriz é definido por suas linhas (horizontal) e colunas (vertical). Por exemplo, uma matriz de 3x2 tem 3 linhas e 2 colunas.

3. **Tipos de Matrizes**  
   Existem vários tipos, incluindo:  
   - Matrizes quadradas (mesmo número de linhas e colunas)  
   - Matrizes retangulares (número diferente de linhas e colunas)  
   - Matrizes diagonais (elementos fora da diagonal principal são todos zero)  
   - Entre outros tipos especiais

4. **Operações**  
   As matrizes podem ser somadas, subtraídas e multiplicadas entre si, seguindo regras específicas. SPor exemplo, a multiplicação de matrizes não é comutativa, ou seja, a ordem dos fatores altera o resultado.

5. **Determinante e Inversa**  
   Para algumas matrizes quadradas, pode-se calcular o determinante, uma propriedade que fornece informações importantes sobre a matriz. Matrizes com determinante diferente de zero possuem uma inversa, que é uma matriz que, ao ser multiplicada pela original, resulta na matriz identidade.

6. **Aplicações**  
   - Matrizes são usadas para resolver sistemas de equações lineares, onde cada linha pode representar uma equação e cada coluna uma variável desconhecida.  
   - Representam transformações lineares entre espaços vetoriais, como rotações, reflexões e escalonamentos em gráficos computacionais.  
   - São utilizadas em matemática avançada para encontrar autovalores e autovetores, úteis na análise de sistemas dinâmicos, mecânica quântica e redução de dimensionalidade em Machine Learning.  
   - Organizam e manipulam dados com múltiplas variáveis por observação, como em pesquisas: cada linha representa uma resposta individual, cada coluna uma pergunta.  
   - Fundamentais em modelos estatísticos lineares, como a regressão linear múltipla, representando variáveis dependentes e independentes.  
   - Matrizes de covariância e correlação ajudam a entender como diferentes variáveis estão relacionadas entre si. Cada elemento representa a covariância ou correlação entre um par de variáveis.

> Matrizes são estruturas essenciais para representar e manipular relações lineares entre variáveis, dados e transformações espaciais. Elas fornecem uma forma compacta e poderosa de resolver uma ampla variedade de problemas teóricos e práticos.



## Trabalhando com Escalares usando NumPy

In [1]:
import numpy as np

In [9]:
escalar1 = 2
escalar = np.array(2)
type(escalar1), type(escalar)

(int, numpy.ndarray)

In [10]:
print(escalar)

2


In [11]:
x = 2 + escalar
print(x)
type(x)

4


numpy.int64

In [18]:
escalar.shape

()

## Vetores

In [15]:
vetor = np.array([1, 2, 3])
type(vetor)

numpy.ndarray

In [16]:
print(vetor)

[1 2 3]


In [17]:
vetor.shape

(3,)

O shape (3,) indica 3 elementos de uma estrutura unidimensional

In [24]:
vetor[0]

np.int64(1)

## Matrizes

In [25]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
type(m)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
m.shape

(3, 3)

O shape (3,3) indica que é uma matriz com 2 dimensões, cada dimensão tem 3 elementos.

In [28]:
print(m[1, 2])

6


## Tensores

Tensores são como vetores e matrizes, mas podem ter n dimensões.

In [43]:
t = np.array([[[1, 2, 2], [3, 4, 4]],\
               [[5, 6, 5], [7, 8, 8]],\
               [[9, 10, 9], [11, 8, 9]]])
print(t)
t.shape

[[[ 1  2  2]
  [ 3  4  4]]

 [[ 5  6  5]
  [ 7  8  8]]

 [[ 9 10  9]
  [11  8  9]]]


(3, 2, 3)

### Mudança de shape entre vetores, matrizes e tensores

In [46]:
vec = np.array([1, 2, 3, 4, 5])
print(vec)
vec.shape

[1 2 3 4 5]


(5,)

In [49]:
x = vec.reshape(5, 1)
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]
 [5]]


(5, 1)

Uso de `flatten` para transformar tensor em vetor:

In [ ]:
t = np.array([[[1, 2], [3, 4]],
             [[5, 6], [7, 8]]])

vetor_flat = t.flatten()
print(vetor_flat)

[1 2 3 4 5 6 7 8]


Cnverter em matriz

In [54]:
matriz = t.reshape(2, 4)
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [55]:
matriz = t.reshape(4, 2)
print(matriz)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## ELement-wise
### Operações Element-wise com Vetores

In [56]:
valores = np.array([1, 2, 3, 4, 5])

valores = valores + 10
print(valores)

[11 12 13 14 15]


In [ ]:
valores = np.array([1, 2, 3, 4, 5])

# outro método,  mais otimizado
valores = np.add(valores, 10)
print(valores)

[11 12 13 14 15]


In [61]:
valores *= 0
print(valores)

[0 0 0 0 0]


### Operações Element-wise com Matrizes

In [64]:
x = np.array([[1, 2], [5, 6]])
print(x)

[[1 2]
 [5 6]]


In [69]:
y = np.array([[2, 4], [3, 7]])
print(y)

[[2 4]
 [3 7]]


In [70]:
x + y

array([[ 3,  6],
       [ 8, 13]])

In [72]:
y + 5

array([[ 7,  9],
       [ 8, 12]])

In [73]:
x + y + 10

array([[13, 16],
       [18, 23]])

In [75]:
(x + y) / 10

array([[0.3, 0.6],
       [0.8, 1.3]])

## DIferença de MUltiplicação de matrizes

### Multiplicação elemento a elemento (elemnt-wise)

**x * y**
multiplicando elemento a elemento:

_obs: não é multiplicação de matrizes_

 Para que a multiplicação elemento a elemento funcione, as matrizes envolvidas devem ter o mesmo tamanho (número de linhas e colunas)

In [77]:
print(x)
print(y)
x * y

[[1 2]
 [5 6]]
[[2 4]
 [3 7]]


array([[ 2,  8],
       [15, 42]])

### Multiplicação de Matrizes

**np.matmul(x, y)** ou  **x @ y** é a multiplicação de matrizes própriamente dita.

In [78]:
np.matmul(x, y)

array([[ 8, 18],
       [28, 62]])

In [79]:
x @ y

array([[ 8, 18],
       [28, 62]])

#### Produto matricial
**np.dot(x, y)**

 Para matrizes **bidimensionais**, np.dot(x, y) é equivalente a np.matmul(x, y).
  Calcula o produto matricial de x e y.

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

O produto escalar (dot product) é a soma dos produtos dos elementos correspondentes nas duas matrizes. Para obter o produto escalar, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.


In [85]:
np.dot(x, y)

array([[ 8, 18],
       [28, 62]])


**np.dot(x, x.T)**: Aqui, x.T é a transposta de x. Esta operação realiza o produto matricial de x com sua transposta. O resultado é uma matriz que representa, de certa forma, o "produto escalar" da matriz com ela mesma, mas em termos de suas linhas ou colunas, dependendo da orientação da multiplicação.


In [87]:
np.dot(x, x.T)

array([[ 5, 17],
       [17, 61]])

#### Magnitude da Matriz

**np.sqrt(np.sum(x ** 2))**: Esta expressão calcula a norma Frobenius da matriz x. Primeiro, eleva cada elemento de x ao quadrado e soma todos esses quadrados. Em seguida, calcula a raiz quadrada do resultado. Isso dá uma medida geral da magnitude da matriz x.

In [89]:
mag = np.sqrt(np.sum(x ** 2))
print(mag)

8.12403840463596


**np.cross(x, y)**: Esta operação calcula o produto vetorial (ou produto cruzado) de x e y. Como x e y são matrizes 2x2, a função np.cross tratará as linhas de cada matriz como vetores e calculará o produto vetorial linha a linha.


In [90]:
np.cross(x, y)

/tmp/ipykernel_2402442/2907437548.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(x, y)


array([ 0, 17])

## Conceitos de Broadcasting do NumPy
Broadcasting no NumPy é um recurso que permite que operações aritméticas sejam realizadas em arrays de diferentes formas e tamanhos.

Esse processo envolve automaticamente "estender" um ou ambos os arrays envolvidos na operação para que eles tenham a mesma forma, permitindo assim que as operações sejam realizadas de maneira elementar.

### Regras de Broadcasting

- Se os arrays não tiverem o mesmo número de dimensões, a forma do array com menos dimensões é preenchida com uns à esquerda.

- Se o tamanho das dimensões corresponder ou se uma das dimensões for 1, o broadcasting será aplicado. Se uma dimensão de um array for 1 e a do outro array for maior que 1, o primeiro array se comportará como se tivesse o tamanho da maior dimensão.

- Se em qualquer dimensão os tamanhos forem diferentes e nenhum deles for 1, ocorrerá um erro, pois o broadcasting não pode ser aplicado.


### Exemplos de Broadcasting


- Adicionando um escalar a um array: Se você adicionar um número (escalar) a um array, o broadcasting estende esse escalar para um array do mesmo tamanho que o original e realiza a adição.


- Operações entre arrays de diferentes tamanhos: Por exemplo, se você tiver um array de forma (3,1) e outro de forma (1,3), o broadcasting permite que esses arrays se comportem como se ambos tivessem forma (3,3) para realizar operações elementares.

https://numpy.org/doc/stable/user/basics.broadcasting.html

## Matrix Product

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

A definição de multiplicação de matrizes indica uma multiplicação linha por coluna, onde as entradas na i-ésima linha de A são multiplicados pelas entradas correspondentes no jth coluna de B e, em seguida, somando os resultados.

A multiplicação de matrizes NÃO é comutativa.

Para encontrar o produto da matriz, usa-se a função `matmul()` do NUmpy.

**O shape das matrizes precisa ser compatível.**

**Regras para o produto das matrizes:**

- O número de colunas na matriz esquerda deve ser igual ao número de linhas na matriz direita.
- A matriz resultante da operação possui o mesmo número de linhas que a matriz esquerda e o mesmo número de colunas que a matriz direita.
- Os dados na matriz esquerda deve ser organizafo como linhas, enquanto os dados na matriz direita devem ser organizados como colunas.
- Ordem importa: MUltiplicar $A.B$ não é o mesmo de $B.A$

In [94]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [99]:
a.shape

(2, 4)

In [96]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [98]:
b.shape

(4, 3)

O número de colunas da matriz $a$ é iguial ao número de linhas da matriz $b$

In [100]:
prod = np.matmul(a, b)
print(prod)

[[ 70  80  90]
 [158 184 210]]


In [101]:
prod.shape

(2, 3)

### Produto Escalar de matrizes

In [102]:
np.dot(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

Dot product com escalares:

In [104]:
k = 5
j = 2

print(np.dot(k, j))

10


Dot product com vetores:

In [105]:
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

print(np.dot(c, d))

32


Dot product com matrizes:

In [114]:
m1 = [[1, 2], [4, 5]]
m2 = [[7, 8], [1, 2]]

print(np.dot(m1, m2))
print("O inverso:")
print(np.dot(m2, m1))

[[ 9 12]
 [33 42]]
O inverso:
[[39 54]
 [ 9 12]]


In [115]:
# Outra forma
m1 = np.array(m1)
m2 = np.array(m2)

m1.dot(m2)

array([[ 9, 12],
       [33, 42]])

In [116]:
np.matmul(m1, m2)

array([[ 9, 12],
       [33, 42]])

Desde que a e b são bidimensionais, np.dot(a, b) e np.matmul(a, b) realizam a mesma operação de multiplicação de matrizes e, portanto, produzem o mesmo resultado.

## Multiplicação com Arrays Multidimensionais

In [120]:
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)
a.shape

(2, 3, 3)

Em caso de Arrays multidimensionais dot e matmul não produzem o mesmo resultado

In [123]:
c = np.matmul(a, b)
print(c, c.shape)

[[[0.13215516 0.31561791 0.53889325]
  [0.10097144 0.21523238 0.40999805]
  [0.29698353 0.34013694 0.32471013]]

 [[0.19292383 0.93027634 1.13792439]
  [0.36713023 1.02611164 1.15316647]
  [0.23003357 1.02834652 1.23356842]]] (2, 3, 3)


In [124]:
d = np.dot(a, b)
print(d, d.shape)

[[[[0.13215516 0.31561791 0.53889325]
   [0.15770139 0.50832693 0.44815978]]

  [[0.10097144 0.21523238 0.40999805]
   [0.14833005 0.39272443 0.29858683]]

  [[0.29698353 0.34013694 0.32471013]
   [0.11017575 0.35648178 0.64744572]]]


 [[[0.33544612 0.73278418 0.98575969]
   [0.19292383 0.93027634 1.13792439]]

  [[0.47135392 0.70414323 1.02220598]
   [0.36713023 1.02611164 1.15316647]]

  [[0.37369009 0.79400687 1.0847261 ]
   [0.23003357 1.02834652 1.23356842]]]] (2, 3, 2, 3)


**Atenção:**

- A função `matmul()` usa o array como uma pilha de matrizes como elementos que residem nos dois últimos índices, respectivamente. 

- A função `dot()`, por outro lado, realiza a multiplicação como a soma dos produtos sobre o último eixo da primeira matriz e o penúltimo da segunda.

- Outra diferença entre `matmul()` e a função `numpy.dot` é que a primeira não pode realizar multiplicação de array com valores escalares.

### Cálculo da Norma

In [125]:
np.sqrt(np.sum(a ** 2))

np.float64(1.9300561836404126)

# Exercícios

### Exercício 1: Soma de Matrizes
Escreva  um  programa  em  Python  que  soma  duas  matrizes  de mesmo  tamanho.  As matrizes devem ser lidas como listas de listas e o resultado deve ser exibido na tela. Apresente a solução com e sem o uso do NumPy. 


In [215]:
l1 = [[1, 2, 3], [4, 5, 6]]
l2 = [[7, 8, 9], [10, 11, 12]]

soma = [[i + j for i, j in zip(l1[0], l2[0])]]

for n in range(1, len(l1)):
    soma.append([i + j for i, j in zip(l1[1], l2[1])])

soma

[[8, 10, 12], [14, 16, 18]]

In [212]:
np.array(l1) + np.array(l2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [162]:
def multiplica_matrizes(l1, l2):
    if len(l1[0]) != len(l2):
        raise ValueError("As matrizes não podem ser multiplicadas, pois o número de colunas da primeira matriz não é igual ao número de linhas da segunda matriz.")
    else:
        resultado = []
        for i in range(len(l1)):
            linha = []
            for j in range(len(l2[0])):
                soma = 0
                for k in range(len(l2)):
                    soma += l1[i][k] * l2[k][j]
                linha.append(soma)
            resultado.append(linha)
        return resultado

In [163]:
# matriz 2x3
l1 = [[1, 2, 3], 
      [4, 5, 6]]

#matriz 3x2
l2 = [[7, 8], 
      [9, 10],
      [1, 2]]

try:  
    print(multiplica_matrizes(l1, l2))
except ValueError as e:
    print("Erro", e)

[[28, 34], [79, 94]]


In [164]:
np.array(l1) @ np.array(l2)

array([[28, 34],
       [79, 94]])


### Exercício 3: Transposição de Matriz
Crie um programa que calcula a transposta de uma matriz. A matriz deve ser inserida pelo usuário e o programa deve exibir a matriz transposta. Apresente a solução com e sem o uso do NumPy.

In [169]:
a = [[1,2,3],
     [4,5,6]]

t = []
for i in range(len(a[0])):
    linha = []
    for j in range(len(a)):
        linha.append(a[j][i])
    t.append(linha)
t


[[1, 4], [2, 5], [3, 6]]

In [221]:
[[a[j][i] for j in range(len(a))] for i in range(len(a[0]))]

[[1, 4], [2, 5], [3, 6]]

In [222]:
np.array(a).T

array([[1, 4],
       [2, 5],
       [3, 6]])


### Exercício 4: Traço de uma Matriz

Desenvolva um script em Python que calcula o traço de uma matriz (soma dos elementos da  diagonal  principal).  O  programa  deve  funcionar  para  matrizes  quadradas  de  qualquer tamanho.  Apresente  a  solução  com  e  sem  o  uso  do  NumPy.


In [233]:
def traco_matriz(a):
    if not all(len(row) == len(a) for row in a):
        print("A matriz deve ser quadrada para calcular o traço.")
        return None
    soma = 0
    for i in range(len(a)):
        for j in range(len(a[i])):
            if i == j:
              soma += a[i][j]
    return soma

In [232]:
matriz = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

traco_matriz(matriz)

15

In [224]:
[sum(matriz[i][j] for i in range(len(matriz)) for j in range(len(matriz[i])) if i == j)]

[15]

In [197]:
np.array(matriz).trace()

np.int64(15)


### Exercício 5: Determinante de uma Matriz

Escreva  uma  função  que  calcula  o  determinante  de  uma  matriz  quadrada.  Utilize  a recursividade ou o método de Laplace para calcular o determinante. Apresente a solução com e sem o uso do NumPy.


In [229]:
# Determinante de uma matriz (Desafio)
def determinante(matriz):
    if not all(len(row) == len(matriz) for row in matriz):
        print("A matriz deve ser quadrada.")
        return None
    elif len(matriz) == 1:
        return matriz[0][0]
    elif len(matriz) == 2:
        return matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0]
    else:
        det = 0
        for c in range(len(matriz)):
            submatriz = [row[:c] + row[c+1:] for row in matriz[1:]]
            det += ((-1) ** c) * matriz[0][c] * determinante(submatriz)
        return det

determinante(matriz)  

0

In [230]:
m = np.array(matriz) 
np.linalg.det(m)

np.float64(0.0)